name: DevSecOps Scan

on:
  push:
    branches: [ mainer, main, master ]
  pull_request:
    branches: [ mainer, main, master ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # 上傳掃描結果到 Security > Code scanning
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          generateSarif: "1"
          uploadSarif: "1"      # 讓結果出現在 Code scanning alerts
