name: DevSecOps Scan

on:
  push:
    branches: [ main, master ,mainer]   # mainer 看起來像是手誤，先拿掉
  pull_request:
    branches: [ main, master,mainer ]
  schedule:
    - cron: "0 2 * * *"          # 每天 10:00 台灣時間（UTC+8）

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    container:
      image: semgrep/semgrep:latest  # 官方建議直接用這個 image 跑 CLI

    steps:
      - uses: actions/checkout@v4

      # 方案A：不綁 Semgrep 平台帳號，直接用公開規則掃描並產出 SARIF
      - name: Run Semgrep scan (CE rules)
        run: |
          semgrep scan \
            --config p/owasp-top-ten \
            --config p/javascript \
            --config p/typescript \
            --config p/secrets \
            --max-target-bytes 0 \        # 取消 1MB 檔案上限，避免被跳過
            --sarif --output semgrep.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
