name: DevSecOps Scan

on:
  push:
    branches: [ master ]     # 你是 master 分支
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"      # 每天 10:00 台灣時間（UTC+8）

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    container:
      image: semgrep/semgrep:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep scan
        working-directory: ./my-app           # ⬅ 指定程式碼所在資料夾
        run: >
          semgrep scan
          --config p/owasp-top-ten
          --config p/javascript
          --config p/typescript
          --config p/secrets
          --max-target-bytes 0
          --sarif --output semgrep.sarif
          .

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: my-app/semgrep.sarif    # ⬅ 路徑要對應 working-directory
